<a href="https://colab.research.google.com/github/bhanu0925/DeepLearning/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Tensors

t1 = torch.tensor(4.)
t1

tensor(4)

In [ ]:
a = [12,3]
type(a)

list

In [ ]:
t1.dtype

torch.float32

In [ ]:
#Vector
t2 = torch.tensor([1.,500,2,4,6])
t2

tensor([  1., 500.,   2.,   4.,   6.])

In [ ]:
t2.dtype

torch.float32

In [ ]:
[1,"s",36.5,True]

In [ ]:
#Metrix

t3 = torch.tensor(
    [
     [4,5,9],
     [9,59,9]
    ]
)

t3.dtype

torch.int64

In [ ]:
# 3 -dim tensors
t4 = torch.tensor([
                   [[11,23,45],
                    [55,77.,88]],
                   
                   [[41,73,45],
                    [56,77,88.]]])

t4

tensor([[[11., 23., 45.],
         [55., 77., 88.]],

        [[41., 73., 45.],
         [56., 77., 88.]]])

In [ ]:
print(t1)
t1.shape

tensor(4)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([  1., 500.,   2.,   4.,   6.])


torch.Size([5])

In [ ]:
print(t3)
t3.shape

tensor([[ 4,  5,  9],
        [ 9, 59,  9]])


torch.Size([2, 3])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 23., 45.],
         [55., 77., 88.]],

        [[41., 73., 45.],
         [56., 77., 88.]]])


torch.Size([2, 2, 3])

In [ ]:

t3 = torch.tensor(
    [
     [4,5,9],
     [9,59]
    ]
)

t3.dtype

ValueError: ignored

In [ ]:
# tensors operation

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic 

y = w * x + b 
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
# Tensor Function

t6 = torch.full((3,3), 77)
t6

tensor([[77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]])

In [ ]:
t3

tensor([[ 4,  5,  9],
        [ 9, 59,  9]])

In [ ]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 4,  5,  9],
        [ 9, 59,  9],
        [77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.7568, -0.9589,  0.4121],
        [ 0.4121,  0.6367,  0.4121],
        [ 0.9995,  0.9995,  0.9995],
        [ 0.9995,  0.9995,  0.9995],
        [ 0.9995,  0.9995,  0.9995]])

In [ ]:
t9 = t8.reshape(3,5,1)

In [ ]:
t9

tensor([[[-0.7568],
         [-0.9589],
         [ 0.4121],
         [ 0.4121],
         [ 0.6367]],

        [[ 0.4121],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995]],

        [[ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995]]])

In [ ]:
t3=[[4,5,9],
                 [5,6,7]]
